Classes and Objects
Classes is a template or blur print for real world entities(Inside classes you have a properties and behaviour are there)
Objects are specific instances of class

The first letter of the name of the class be in capital

In [13]:
class Phone: 
    
    #start of by creatiing methods
    
    def make_call(self):
        print("Making a phone call")
        
    def play_game(self):
        print("Playing a game")
    

In [9]:
p1 = Phone()

In [3]:
p1.make_call()

Making a phone call


In [10]:
p1.play_game()

Playing a game


In [12]:
#New class

In [34]:
class Phone:
    
    def add_color(self,color):
        self.color=color
        
    def add_cost(self,cost):
        self.cost=cost
    def add_model(self,model):
        self.model=model
        
    def show_color(self):
        return self.color
    
    def show_cost(self):
        return self.cost
    
    def show_model(self):
        return self.model
    
    
    def make_call(self):
        print("Making a phone call")
        
    def play_game(self):
        print("Playing a game")
    

In [35]:
p2 = Phone()

In [17]:
p2.add_color("Red")

In [18]:
p2.add_cost("20000")

In [20]:
p2.show_color()

'Red'

In [28]:
p2.show_cost()

'20000'

In [37]:
p2.add_model("flip")

In [38]:
p2.show_model()

'flip'

In [40]:
p3 = Phone()

In [45]:
p3.add_color("Black")
p3.add_cost(25000)
p3.add_model("flat")

In [42]:
p3.show_color()
p3.show_cost()

25000

In [26]:
p3.show_color()

'Black'

In [47]:
p3.show_model()

'flat'

# Inheritance in Python

In [48]:
class Iphone(Phone):
    
    def cure_cancer(self):
        print("I can cure cancer")

In [49]:
ip1 = Iphone()

In [50]:
ip1.cure_cancer()

I can cure cancer


In [51]:
ip1.add_color("Grey violet")

In [52]:
ip1.add_cost(34870)

In [53]:
ip1.add_model("Slim")

In [54]:
ip1.show_color()

'Grey violet'

In [55]:
ip1.show_cost()

34870

In [56]:
ip1.show_model()

'Slim'

In [57]:
import pandas as pd

In [63]:
import numpy 

In [70]:
ip1.cure_cancer

<bound method Iphone.cure_cancer of <__main__.Iphone object at 0x041E4190>>

In [69]:
ip1.make_call

<bound method Phone.make_call of <__main__.Iphone object at 0x041E4190>>

In [133]:
ip1.show_color

<bound method Phone.show_color of <__main__.Iphone object at 0x041E4190>>

# NumPy Library

In [71]:
import numpy as np

In [74]:
n1 = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2],[4,1,2,3]])  #Multi dimensional array

In [75]:
n1

array([[1, 2, 3, 4],
       [2, 3, 4, 1],
       [3, 4, 1, 2],
       [4, 1, 2, 3]])

In [78]:
n2 = np.array([1,23,4])     #Single dimensional array

In [77]:
n2

array([ 1, 23,  4])

In [79]:
type(n1)

numpy.ndarray

In [80]:
type(n2)

numpy.ndarray

In [81]:
n2 = np.zeros((1,4))

In [82]:
n2

array([[0., 0., 0., 0.]])

In [83]:
n3 = np.zeros((10,10))

In [84]:
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
n2 = np.full((5,5),5)

In [88]:
n2

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [91]:
n2 = np.arange(12,17)

In [92]:
n2

array([12, 13, 14, 15, 16])

In [94]:
n2 = np.arange(12,27,3)

In [98]:
n2

array([12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5])

In [97]:
n2 = np.arange(12,27,0.5)

In [113]:
n1 = np.random.randint(1,90,15)

In [115]:
n1.shape

(15,)

In [118]:
n2.shape

(30,)

In [123]:
n5 = np.array([[2,3,4]])

In [120]:
n4.shape

(1, 3)

In [121]:
n4.shape = (3,1)

In [122]:
n4

array([[2],
       [3],
       [4]])

In [124]:
n4*n5

array([[ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16]])

In [125]:
n1 = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2],[4,1,2,3]])

In [126]:
n2 = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2],[4,1,2,3]])

In [127]:
n1+n2

array([[2, 4, 6, 8],
       [4, 6, 8, 2],
       [6, 8, 2, 4],
       [8, 2, 4, 6]])

In [129]:
n1-n2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [130]:
n1/n2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [131]:
n1*(n2+n1)

array([[ 2,  8, 18, 32],
       [ 8, 18, 32,  2],
       [18, 32,  2,  8],
       [32,  2,  8, 18]])

In [132]:
n1*n2

array([[ 1,  4,  9, 16],
       [ 4,  9, 16,  1],
       [ 9, 16,  1,  4],
       [16,  1,  4,  9]])

In [135]:
np.sum([n1,n2])

80

In [137]:
np.sum([n1,n2],axis=0)

array([[2, 4, 6, 8],
       [4, 6, 8, 2],
       [6, 8, 2, 4],
       [8, 2, 4, 6]])

In [138]:
np.sum([n1,n2],axis=1)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [139]:
n6 = np.arange(10,20,5)

In [141]:
n7 = np.arange(20,30,5)

In [142]:
np.sum([n6,n7],axis=0)

array([30, 40])

In [144]:
np.sum([n6,n7],axis=1)

array([25, 45])

In [145]:
n6

array([10, 15])

In [146]:
n7

array([20, 25])

# JoiNIng NUMPY ARRAYS

In [147]:
n1 = np.array([1,2,3,4])

In [158]:
n2 = np.arange(10,17,2)

In [160]:
n3

array([4, 1, 8, 2])

In [149]:
n3 = np.random.randint(1,10,4)

In [159]:
n2

array([10, 12, 14, 16])

In [163]:
np.vstack((n1,n2,n3))

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [ 4,  1,  8,  2]])

In [164]:
np.hstack((n1,n2,n3))

array([ 1,  2,  3,  4, 10, 12, 14, 16,  4,  1,  8,  2])

In [166]:
np.column_stack((n1,n2,n3))

array([[ 1, 10,  4],
       [ 2, 12,  1],
       [ 3, 14,  8],
       [ 4, 16,  2]])

## Pandas - Panal Data



# pandas data structures 
Single dimensional - series Object
Multi dimensional - Data- frame